project:
  type: website
  output-dir: docs

website:
  title: "DS4i Writeup"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Report"
        href: DS4i_writeup.qmd
      - text: "LLM"
        href: llm_use.qmd
      - text: "Plagiarism Declaration"
        href: plag_decl.qmd
      - text: "Final Model"
        href: mlp_model_report.html
        
