---
title: "Plagiarism Declaration"
format: html
---

**Department of Statistical Sciences Plagiarism Declaration form**

***A copy of this form, completed and signed, to be attached to all coursework submissions to the Statistical Sciences Department. Submissions without this form will not be marked.***

**COURSE CODE**: STA5073Z

**COURSE NAME**: Data Science for Industry

**STUDENT NAMES**: Don Gwese; Matthew Russell; Nina Lewis; Aidan Thomas; Sanana Mwanawina

**STUDENT NUMBERS**: GWSDON002; RSSMAT013; LWSNIN001; THMAID005; MWNSAN002

1.  I know that plagiarism is wrong. Plagiarism is to use another’s work and pretend that it is one’s own.
2.  I have used a generally accepted citation and referencing style. Each contribution to, and quotation in, this tutorial/report/project from the work(s) of other people has been attributed, and has been cited and referenced.
3.  This tutorial/report/project is our own work.
4.  I have not allowed, and will not allow, anyone to copy our work with the intention of passing it off as his or her own work.
5.  I acknowledge that copying someone else’s assignment or essay, or part of it, is wrong, and declare that this is our own work.

Note that agreement to this statement does not exonerate you from UCT’s Academic Misconduct policy (https://uct.ac.za/media/584410).

**Signature**: D.Gwese; M.Russell; N.Lewis; A.Thomas; S.Mwanawina

**Date**: 28 September 2025
