---
title: "project_template"
format: html
execute:
  echo: false
  warning: false
  message: false
  results: hide
editor: visual
---

```{r setup}

#libraries 

library(kableExtra)
library(tidyverse)
library(ggplot2)
library(ggpubr)

#theme for ggplot2, let me know if you do not like this theme and we can change it :)

#Theme for ggplot2 
theme_set(
  theme_bw(base_size = 9) +
    theme(
      plot.title   = element_text(hjust = 0.5, size = 9),
      panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5),
      # keep grids but make them subtle
      panel.grid.major = element_line(colour = "grey85", linewidth = 0.3),
      panel.grid.minor = element_line(colour = "grey92", linewidth = 0.2),
      # base-R style text/ticks
      axis.text  = element_text(colour = "black"),
      axis.title = element_text(colour = "black"),
      axis.ticks = element_line(colour = "black", linewidth = 0.3)
    )
)



#making geompoint have hollow circles
update_geom_defaults(
  "point",
  list(size = 1, alpha = 0.9, shape = 21, colour = "black")
)


```

```{r}

#Assistance for my teamates!

#Once you have opened this project on your machine, you will notice that in the branches tab in the top right corner you will have your own branch. 

#1. You can switch to that by clicking on the drop down menu and clicking the branch, or typing the following code into the terminal.

#git checkout [insert your branch name here]

#2. VERY IMPORTANT. You need to tell R to link itself to the remote version of your branch (the part that is on the internet). Do this by adding this command into the terminal 

#git push push -u origin [insert branch name here]

#do this for your branch and for the main branch as well.

#3. Work primarily on your own branch. When ready, you can merge your changes onto the main branch, but check with your teamates first whether its okay to do this so we do not run into any conflicts! To get the latest changes from main, you need to switch to main, enter a command to get the latest changes, and then feel free to switch back to your branch and merge. The code to do this, is

#git checkout main (switches to main branch)
#git pull origin main (gets latest changes from the internet)

#git checkout [insert your branch name]
#git merge main (merges your branch with main)

#after this you are good to go. To add your changes to main at a later stage :


#git checkout main
#git merge [insert your branch]

#But make sure you switch to main and pull the latest changes first before you do this and double check with your teamates if this is okay!



```

```{r table_code}
#example code to use for tables. 

eg <- data.frame(x = c("a","b", "c"),
                 y = c(1:3),
                 z = c(100,104,106))

kable(eg, format = "html",
      digits = 4,
      caption = "Initial Exploration") %>%
  kable_styling(
    bootstrap_options = c("hover"),
    full_width = FALSE
  ) %>%
  footnote(general = "All values rounded to 4 decimal places.")




```

```{r ggplot_example}

ggplot(data = eg, aes(x = y, y = z)) +
  geom_point()+
  geom_line()



```
