<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DS4I - Project Writeup – DS4i Writeup</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.34.0/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DS4i Writeup</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./DS4i_writeup.html" aria-current="page"> 
<span class="menu-text">Modelling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./llm_use.html"> 
<span class="menu-text">LLM use</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DS4I - Project Writeup</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="av.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><span style="font-size:12px">Photo by Nicolas Cool on Unsplash</span></p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
</section>
<section id="introduction-and-literature-review" class="level2">
<h2 class="anchored" data-anchor-id="introduction-and-literature-review">Introduction and Literature Review</h2>
<p>Snow avalanches are a hazard in snow-prone regions. Unlike more alpine regions, avalanches in Scotland rarely impact settlements and infrastructure, but pose risks to recreational users (Bain, 2024; Diggins, 2009; Ward, 1980; WSL Institute for Snow and Avalanche Research SLF [WSL], 2016). Rising popularity of winter activities such as climbing, walking, and skiing has increased exposure to avalanche-prone terrain, resulting in injuries and occasional fatalities each year (Scottish Avalanche Information Service [SAIS], 2024; Webster, 2020, WSL, 2016). These risks prompted studies of Scottish snowpack and forecasting strategies beginning in the 1970s (Langmuir, 1970; Spink, 1970; Beattie, 1976; Ward, 1980; Ward et al., 1985). However, early work was largely descriptive, relying on snow-pit measurements and expert judgement. Building on this, Ward (1984a and 1984b) applied one of the first predictive avalanche forecasting models for Scotland.</p>
<p>Avalanche modelling is inherently complex, where predictions depend on multiple interacting factors (Choubin et al., 2019; Helbig et al., 2015; Hendrick et al., 2023; Pozdnoukhov et al., 2008; Singh &amp; Ganju, 2008). This challenge is heightened in regions with variable weather (Sharma &amp; Ganju, 1999). Early statistical methods, like nearest neighbours, supported forecasters by relating current weather to past avalanche events, however, were prone to overfitting and struggled with high-dimensional data (Blagovechshenskiy et al., 2023; Kala et al., 2025; Pozdnoukhov et al., 2018; Singh &amp; Ganju, 2008). Using a dataset from Lochaber, Scotland, Pozdnoukhov et al.&nbsp;(2008) reported that support vector machines (SVMs) performed similarly to nearest neighbours while handling high-dimensional data more effectively and producing richer forecasts. SVMs have also proven successful in Iran, India, Switzerland, and Tibet (Choubin et al., 2019; Rahmati et al., 2019; Schirmer et al., 2009; Tiwari et al., 2021; Wen et al., 2022).&nbsp;</p>
<p>Recently, more complex machine learning (ML) algorithms (regression trees, random forests, neural networks) have demonstrated strong predictive performance in avalanche forecasting (Blagovechshenskiy et al., 2023; Choubin et al., 2019; Gauthier et al., 2025; Hendrick et al., 2023; Rahmati et al., 2019; Singh &amp; Ganju, 2018; Tiwari et al., 2021; Wen et al., 2022). Avalanche datasets are often high-dimensional, and using forecaster-led feature selection can be highly subjective (Helbig et al., 2015; Pozdnoukhov et al., 2008). Hybrid approaches combining ML tools with expert-led feature selection have shown practical value (Gauthier et al., 2025). However, fully data-driven forecasting methods, particularly neural networks (NNs), offer important advantages.</p>
<p>NNs simulate brain processes through interconnected nodes, capturing complex, nonlinear relationships (Blagovechshenskiy et al., 2023; Sharma et al., 2023; Tu, 1996). By processing inputs simultaneously, patterns are learned without prior knowledge of which variables matter most (Blagovechshenskiy et al., 2023; Fromm &amp; Schonberger, 2022; Sharma et al., 2023). Applications in Switzerland, Kazakhstan, and India show that NNs not only perform strongly but can assess the relative importance of variables (Fromm &amp; Schonberger; Sharma et al., 2023; Singh &amp; Ganju, 2008). This makes them particularly well suited for high-dimensional avalanche datasets and situations with limited domain knowledge or uncertain predictors.</p>
<p>Despite advances in data-driven avalanche forecasting worldwide, research specific to Scotland remains limited in three ways:</p>
<ol type="1">
<li>Few published studies exist (only 9 relevant peer-reviewed papers exist on Scopus, with the most recent study conducted in 2011 (keywords: ( “avalanche forecasting” OR “avalanche prediction” ) AND Scotland)).</li>
<li>The restricted range of statistical approaches explored (only KNN and SVM) (Heierli et al., 2004; Pozdnoukhov et al., 2008; Pozdnoukhov et al., 2011; Purves et al., 2003).</li>
<li>The focus on only a few regions in Scotland (primarily the Cairngorms and Lochaber regions).</li>
</ol>
<p>This limited interest likely stems from the highly localised nature of avalanche risk in Scotland, which generally occurs in remote areas, affecting relatively few people (Diggins, 2009; SAIS, 2024). Nevertheless, improved avalanche forecasting is increasingly important under changing climate conditions, which may alter snowpack properties and avalanche risk (Gauthier et al., 2025; Werritty &amp; Sugden, 2013). A detailed discussion of climate change, however, is beyond this paper’s scope.</p>
<p>The present study aims to extend forecasting research in Scotland both spatially and methodologically by applying three NNs (convolutional (CNN), recurrent (RNN), and a feedforward multilater perceptron (FFNN-MLP)) trained on combined data from the following six regions of Scotland: Creah Meagaidh, Glencoe, Lochaber, Northern Cairngorms, Southern Cairngorms, and Torridon. Each model was chosen for its particular strengths: the FFNN-MLP works well with categorical predictors, the CNN is good at identifying spatial and short-term temporal patterns, and the RNN is suited to capturing longer-term sequential trends over time.</p>
<p>Avalanche risk is sequential in nature because current conditions are influenced by how weather and snowpack have developed over previous days, weeks, or months. For this reason, we hypothesise that the CNN and RNN will perform better than the FFNN-MLP, as they can account for these temporal patterns.</p>
</section>
<section id="context-and-dataset" class="level2">
<h2 class="anchored" data-anchor-id="context-and-dataset">Context and Dataset</h2>
<p>Scotland has a mild, wet, temperate maritime climate influenced by the North Atlantic Ocean and persistent south-westerly winds (Pozdnoukhov et al., 2008; Scottish Government, 2011). These conditions produce rapid temperature changes, frequent heavy precipitation (snow or rain), and strong winds. With its highest peak, Ben Nevis (1345 m), Scotland’s mountains are low compared to alpine ranges (~4000 m), resulting in a snowpack that is typically shallower, wetter, and more variable (Britannica, 2025; Pozdnoukhov et al., 2008; WSL, 2016). Rapid freeze-thaw cycles, rain-on-snow, and wind redistribution further destabilise snow, creating avalanche risks that can appear and disappear within a short time (Diggins, 2009; Pozdnoukhov et al., 2008; Purves et al., 2003; Scottish Government, 2011). Snowpack conditions also differ regionally; the West is strongly maritime, with mild and wet winters, while the North and East are colder and drier (MetOffice, 2010). Scotland’s climate is thus highly variable spatially and temporally, adding to the complexity of avalanche risk prediction.</p>
<p>This paper uses a 15-year archive of avalanche forecasts from Scotland across the six areas of Creah Meagaidh, Glencoe, Lochaber, Northern Cairngorms, Southern Cairngorms, and Torridon, produced by the SAIS (2025). <a href="#fig-map-obs" class="quarto-xref">Figure&nbsp;1</a> illustrates the spatial distribution of observations, with points marking individual events and labels indicating area locations. Total observations by area and hazard category (<a href="#tbl-area-hazard" class="quarto-xref">Table&nbsp;1</a>) reflect differences in observation frequency rather than absolute avalanche activity. Cairngorms (Northern and Southern) and Lochaber, located in the colder and drier North and East, have the most recorded observations, whereas Torridon in the maritime West has substantially fewer. “Low” and “Moderate” hazard levels dominate across all areas, while “High” hazard events are rare and concentrated in Northern Cairngorms and Lochaber.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-map-obs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-map-obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-map-obs-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-map-obs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Observed avalanche hazard (OAH): Scotland.
</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div id="tbl-area-hazard" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-area-hazard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Overall total observations by area and hazard category.
</figcaption>
<div aria-describedby="tbl-area-hazard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 27%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 6%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Area</th>
<th style="text-align: right;">Low</th>
<th style="text-align: right;">Moderate</th>
<th style="text-align: right;">Considerable -</th>
<th style="text-align: right;">Considerable +</th>
<th style="text-align: right;">High</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Creag Meagaidh</td>
<td style="text-align: right;">636</td>
<td style="text-align: right;">545</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">1812</td>
</tr>
<tr class="even">
<td style="text-align: left;">Glencoe</td>
<td style="text-align: right;">716</td>
<td style="text-align: right;">524</td>
<td style="text-align: right;">405</td>
<td style="text-align: right;">109</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">1812</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lochaber</td>
<td style="text-align: right;">597</td>
<td style="text-align: right;">498</td>
<td style="text-align: right;">506</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">1773</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northern Cairngorms</td>
<td style="text-align: right;">655</td>
<td style="text-align: right;">567</td>
<td style="text-align: right;">501</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">1891</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Southern Cairngorms</td>
<td style="text-align: right;">751</td>
<td style="text-align: right;">546</td>
<td style="text-align: right;">383</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">1787</td>
</tr>
<tr class="even">
<td style="text-align: left;">Torridon</td>
<td style="text-align: right;">678</td>
<td style="text-align: right;">373</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1143</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><br></p>
<p>Data span winters (November to April) from the December 2009 to March 2025. Predictors are categorised into: (1) position and topography, (2) weather, and (3) snowpack test, all collected at the forecast location. Each observation includes the date and the forecast area (metadata). For an overview of the predictors available, see <a href="#tbl-pred" class="quarto-xref">Table&nbsp;2</a> .</p>
<div class="cell">
<div id="tbl-pred" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pred-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Overview of predictor variables available in the avalanche forecast dataset.
</figcaption>
<div aria-describedby="tbl-pred-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predictor_Group</th>
<th style="text-align: left;">Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Metadata</td>
<td style="text-align: left;">date, area</td>
</tr>
<tr class="even">
<td style="text-align: left;">Position and Topography</td>
<td style="text-align: left;">longitude, latitude, altitude, aspect of slope, incline of slope</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weather</td>
<td style="text-align: left;">air temperature, wind direction, wind speed, cloud cover, precipitation code, snowdrift, total snow depth, foot penetration, ski penetration, rain observed at 900m elevation, summit air temperature, summit wind direction, summit wind speed</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snowpack Test</td>
<td style="text-align: left;">max. temperature gradient, max. hardness gradient, no.settle, snow.index, insolation, crystals, wetness, AV.Cat, and snow temperature</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<section id="a.-feature-map-correlations" class="level3">
<h3 class="anchored" data-anchor-id="a.-feature-map-correlations">a. Feature Map Correlations</h3>
<p>The Scottish avalanche dataset contains several features that are moderately to strongly correlated, while others appear largely independent (<a href="#fig-feat-cor" class="quarto-xref">Figure&nbsp;2</a>). The presence of correlated variables is not inherently problematic, since NNs can learn non-linear interactions. However, strong correlations can increase the risk of overfitting if the network memorises patterns rather than generalising to new data.</p>
<p>The highest correlation found was between <em>summit.air.temperature</em> and <em>air.temperature</em> (r = 0.85), indicating strong redundancy. Nevertheless, both variables were retained as each likely capture a different aspect relevant to forecasting (i.e., summit conditions versus broader conditions). <em>Air.temperature</em> is an identified key driver of avalanche conditions and is expected to be an important predictor in the NNs (Fromm &amp; Schonberger, 2022; Gauthier et al., 2025; Pozdnoukhouv et al., 2018; Souckova et al., 2022; Ward,1980). Exploration of <em>air.temperature</em> across <em>observed.avalanche.hazard (OAH)</em> levels further supports its importance in forecasting (<a href="#fig-box-OAH" class="quarto-xref">Figure&nbsp;3</a>). Higher hazard categories are generally associated with lower observed <em>air.temperatures</em>, with “Considerable-”, “Considerable+”, and “High” hazards centred below 0 °C. “Low” hazard days show medians above freezing and wider variability. The transition at “Moderate” hazard, where temperatures cluster around 0 °C, reflects conditions that can either stabilise or destabilise the snowpack through freeze-thaw cycles. These patterns highlight Scotland’s sensitivity to rapid temperature shifts and their impact on avalanche activity (Diggins, 2009; Pozdnoukhov et al., 2008).</p>
<p>Other moderate correlations (0.5&lt;|r|&lt; 0.80) remain informative and manageable for NNs.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-feat-cor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-feat-cor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-feat-cor-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-feat-cor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Map of feature correlations.
</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-box-OAH" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-box-OAH-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-box-OAH-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-box-OAH-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Distribution of air temperature across observed avalanche hazard (OAH).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="b.-precipitation-type" class="level3">
<h3 class="anchored" data-anchor-id="b.-precipitation-type">b. Precipitation Type</h3>
<p>The distribution of <em>OAH</em> levels varies across different precipitation types (<a href="#fig-precip-bar" class="quarto-xref">Figure&nbsp;4</a>). “Low” hazard predominates under conditions of none (0) or trace (2) precipitation, whereas higher hazard categories become increasingly prevalent as snowfall intensity increases. Heavy snow (level 10) is associated with a substantially larger share of “Considerable” and “High” hazard ratings (81.9%). This aligns with existing knowledge of the Scottish climate, where rapid weather shifts and frequent rain or snow-on-snow events contribute to unstable snowpack conditions (Diggins, 2009; Pozdnoukhov et al., 2008; Purves et al., 2003; Ward, 1980).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-precip-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-precip-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-precip-bar-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-precip-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Precipitation type vs observed avalanche hazard (OAH).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="c.-seasonality" class="level3">
<h3 class="anchored" data-anchor-id="c.-seasonality">c.&nbsp;Seasonality</h3>
<p>Monthly <em>OAH</em> patterns reveal clear seasonal trends (<a href="#fig-season-bar-hist" class="quarto-xref">Figure&nbsp;5</a>). Early (November-December) and late (April-May) months are dominated by “Low” and “Moderate” hazards, while mid-season (Jan-Mar) sees more “Considerable” and “High” hazards. Most forecasts occur between December-March, highlighting the period of greatest avalanche risk (SAIS, 2024). These patterns reflect cyclical snowpack development, with mid-winter weather instability driving higher-risk avalanches (Diggins, 2009; Podzdnoukhov et al., 2008; Purves et al., 2003).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-season-bar-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-season-bar-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-season-bar-hist-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-season-bar-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Seasonality of observed avalanche hazard (OAH): Nov–May.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="d.-fah-vs-oah" class="level3">
<h3 class="anchored" data-anchor-id="d.-fah-vs-oah">d.&nbsp;FAH vs OAH</h3>
<p>Lastly, <a href="#fig-FAH-OAH" class="quarto-xref">Figure&nbsp;6</a> shows the relationship between <em>forecast.avalanche.hazard (FAH)</em> (day <em>t</em>) and <em>OAH</em> (day <em>t+1</em>). Each column sums to 100%, showing how outcomes were distributed for each forecast level. “Low” forecasts were highly accurate (86.51%), while intermediate levels (“Moderate”, “Considerable-”) had weaker agreement, often spilling into neighbouring categories. “High” forecasts were least reliable, frequently over-predicting extreme conditions.</p>
<p>The agreement between <em>OAH</em> and <em>FAH</em> are highest in stable “Low”-risk conditions and lowest at the extremes, with middle categories showing uncertainty.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-FAH-OAH" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FAH-OAH-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-FAH-OAH-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FAH-OAH-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: FAH (day t) → OAH (day t+1) proportions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Class imbalances will need to be addressed during model training to ensure the network does not simply default to predicting the most common outcomes.</p>
</section>
</section>
<section id="data-cleaning-and-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-and-feature-engineering">Data Cleaning and Feature Engineering</h2>
<p>Feature engineering focused on creating temporal variables to capture trends not natively handled by a feedforward neural network (FFNN). Given that EDA highlighted that <em>OAH</em> varies according to the season and time of year, several variables were derived.</p>
<p>Before removing observations with extensive missing values, we extracted the time of day, day of the week, month, and year from each date. Next, a categorical variable for each avalanche season (December-April, 2009-2025) was created to account for the observed year-on-year increase in risk.</p>
<p><a href="#tbl-missing-val" class="quarto-xref">Table&nbsp;3</a> presents the percentage of missing values for features with incomplete data. <em>Av.Cat</em> was removed because its meaning was unclear and it contained implausible values (e.g., NA, 3, -2, 2, 1, 4, 8800, -1, 0, 1021, 4400, -9999, 99, 88, 44, 5031, 121). <a href="#fig-ski-summit-wind" class="quarto-xref">Figure&nbsp;7</a> shows no clear relationship between <em>ski.penetration</em> and <em>OAH</em>, except for “High” risk avalanches; we therefore excluded it since snowfall effects are likely better represented by other variables. <em>Summit.wind.direction</em> (12.35% missing) was also dropped for lack of a discernible trend.</p>
<div class="cell">
<div id="tbl-missing-val" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-missing-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Missing value exploration.
</figcaption>
<div aria-describedby="tbl-missing-val-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-hover do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Missing (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AV.Cat</td>
<td style="text-align: right;">23.3718</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ski.Pen</td>
<td style="text-align: right;">22.5283</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Summit.Wind.Dir</td>
<td style="text-align: right;">12.3512</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crystals</td>
<td style="text-align: right;">9.2587</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Summit.Wind.Speed</td>
<td style="text-align: right;">8.5184</td>
</tr>
<tr class="even">
<td style="text-align: left;">Summit.Air.Temp</td>
<td style="text-align: right;">7.0659</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Snow.Index</td>
<td style="text-align: right;">6.9815</td>
</tr>
<tr class="even">
<td style="text-align: left;">Max.Temp.Grad</td>
<td style="text-align: right;">6.6535</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Max.Hardness.Grad</td>
<td style="text-align: right;">5.8945</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wetness</td>
<td style="text-align: right;">5.3978</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Insolation</td>
<td style="text-align: right;">4.7512</td>
</tr>
<tr class="even">
<td style="text-align: left;">OAH</td>
<td style="text-align: right;">4.2452</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Snow.Temp</td>
<td style="text-align: right;">3.8422</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aspect</td>
<td style="text-align: right;">3.3268</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No.Settle</td>
<td style="text-align: right;">2.7083</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total.Snow.Depth</td>
<td style="text-align: right;">1.5275</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wind.Dir</td>
<td style="text-align: right;">1.4806</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wind.Speed</td>
<td style="text-align: right;">0.4967</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Foot.Pen</td>
<td style="text-align: right;">0.3936</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incline</td>
<td style="text-align: right;">0.3374</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Air.Temp</td>
<td style="text-align: right;">0.3186</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cloud</td>
<td style="text-align: right;">0.2718</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alt</td>
<td style="text-align: right;">0.0562</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> All values rounded to 4 decimal places.</td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ski-summit-wind" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ski-summit-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-ski-summit-wind-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ski-summit-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Boxplots of ski penetration and summit wind direction by avalanche hazard category.
</figcaption>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Lastly, we dropped high-cardinality categorical variables, including <em>osgrid</em> and <em>location. Osgrid</em> appeared to be an ID variable with &gt;3000 unique values, which would make one-hot encoding overly complex and was unlikely to indicate risk. <em>Location</em> was also removed, since <em>latitude</em>, <em>longitude</em>, and <em>area</em> already captured spatial information more effectively.</p>
<p>After removing variables, 36% of samples remained incomplete and were subsequently dropped. While retaining more observations would be ideal, the remaining ~7000 were sufficient for representative results.</p>
</section>
<section id="modeling-methodology" class="level2">
<h2 class="anchored" data-anchor-id="modeling-methodology">Modeling Methodology</h2>
<p>Three main models were used in this project to exploit different structural properties of the data: a convolutional neural network (CNN), a recurrent neural network (RNN), and a feedforward multilayer perceptron neural network network (FFNN-MLP). The FFNN-MLP was expected to handle categorical predictors (e.g., forecasted avalanche risk) effectively, while the CNNs and RNNs were targeted at uncovering temporal or sequential patterns.</p>
<p>CNNs process data by applying convolutional filters (small weight matrices) that slide across the input space. Each filter computes dot products with local patches of the data, producing feature maps that emphasise spatial or temporal patterns based on the type of filters used. Non-linear activations are then applied, followed by pooling layers to down-sample the maps and reduce dimensionality while preserving key information. Multiple convolutional layers can be stacked, though two layers were found to balance complexity and generalisation. The below interactive animation aims to illustrate how the filtering process works.</p>
<iframe src="cnn_filter_animation_quarto_ready_html.html" width="672" height="400px" data-external="1">
</iframe>
<div style="font-size: 0.6em; color: black; text-align: left; font-weight: bold">
<p>Credit: OpenAI (2025a and 2025b)</p>
</div>
<p>RNNs are designed to capture sequential dependencies by incorporating feedback connections. At each time step, the hidden state depends not only on the current input but also on the state from the previous step. This architecture makes RNNs well suited for modeling temporal dynamics in sequential data.</p>
<p>A FFNN-MLP consists of an input layer, hidden layers of perceptron nodes, and an output layer. Each hidden node computes a weighted sum of its inputs, applies a non-linear activation, and forwards the result to the next layer. The weights are initialised randomly and updated through backpropogation using an optimiser such as gradient descent. Activation functions (e.g., ReLu, sigmoid) introduce non-linearity enabling the model to capture complex relationships between predictors and the target.</p>
<section id="data-preprocessing-of-neural-networks-models" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing-of-neural-networks-models">Data Preprocessing of Neural Networks models</h3>
<p>To prepare the data for CNN and RNN, we constructed a 3-dimensional array (number of samples × the time window length × the number of features). Each training sample was created by sliding a fixed window across the data. Within the array, columns represent time steps, and depth represent data features. Since we predict one day ahead, each sample represents the observations within the window, for the next day prediction. Data were standardised to avoid distortion from differing feature scales, and one-hot encoded so each categorical variable is split into multiple binary variable demarcating each category.</p>
<p>To preserve temporal trends for the CNN and RNN, the train and test split was not randomly shuffled. Instead, the first 80% of records were used for training, while the remainder was used for testing, similar to the approach of Fromm and Schonberger (2022).</p>
</section>
<section id="convolutional-neural-network" class="level3">
<h3 class="anchored" data-anchor-id="convolutional-neural-network">Convolutional Neural Network</h3>
<p>CNN and RNN hyperparameter selection involved two stages. Firstly, several candidate datasets were created with time windows of 3-days, 7-days, 30-days and 120-days. A narrow search was used, training many models to identify the most appropriate window based on validation accuracy, estimated using cross-validation with a 20% holdout set. All models were trained for 60 epochs, except the FFNN-MLP.</p>
<p>In the second stage, a broader grid-search was conducted on the chosen window, selecting the model with the highest validation accuracy. In all our tests presented for the CNN, we assessed architectures with two convolutional layers using the ReLU function in those latent layers, and the softmax function in our input layer to create the class predictions. More complex architectures did not perform meaningfully better. Measures to control for class imbalance were taken for both the CNN and RNN by calculating weights, inversely proportional to the frequency of observations of that class in the training set.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cnn-window" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cnn-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-cnn-window-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cnn-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: CNN prediction window search.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Considering <a href="#fig-cnn-window" class="quarto-xref">Figure&nbsp;8</a> above, we chose a 7-day prediction window. Overall, most models performed best with 3-7 days, while 30- and 120-day windows were meaningfully worse. Validation accuracy was competitive between 3 and-7-days. However, 7-days appeared more robust, as some 3-day models showed much lower accuracy at the extremes.</p>
<div class="cell">
<div id="tbl-expan-grid" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-expan-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Expanded grid-search hyperparameters and values.
</figcaption>
<div aria-describedby="tbl-expan-grid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-hover do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">hyperparameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">filters1</td>
<td style="text-align: left;">16, 32, 64</td>
</tr>
<tr class="even">
<td style="text-align: left;">filters2</td>
<td style="text-align: left;">16, 32, 64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kernel_sz</td>
<td style="text-align: left;">5, 15</td>
</tr>
<tr class="even">
<td style="text-align: left;">drop1</td>
<td style="text-align: left;">0.5, 0.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drop2</td>
<td style="text-align: left;">0.5, 0.7</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cnn-search-viz" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cnn-search-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-cnn-search-viz-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cnn-search-viz-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Top 30 configurations by validation accuracy for CNN.
</figcaption>
</figure>
</div>
</div>
</div>
<p>After completing the initial window search, an expanded grid-search using the hyperparameters presented in <a href="#tbl-expan-grid" class="quarto-xref">Table&nbsp;4</a> was conducted. The validation accuracy for the top 30 models is presented in <a href="#fig-cnn-search-viz" class="quarto-xref">Figure&nbsp;9</a> .The best performing model during the initial prediction window search (the first stage of the search) achieved a validation accuracy of 67, while the top model using the chosen window in the second stage of the search reached 69.1%. We stuck with this model, as validation accuracy had not improved meaningfully over the course of the expanded search. The final selected model involved 32 filters in the first layer, followed by a dropout of 70%, then 16 layers in the second layers, followed by dropout of 70% and global average pooling into the final output layer, and 5 Kernels (Filters).</p>
</section>
<section id="recurrent-neural-network" class="level3">
<h3 class="anchored" data-anchor-id="recurrent-neural-network">Recurrent Neural Network</h3>
<p>The approach for the RNN was the same as the CNN discussed above. Firstly, a search over numerous candidate window sizes were completed, and a subsequent expanded search was done as well. In <a href="#fig-rnn-window" class="quarto-xref">Figure&nbsp;10</a> below, the validation accuracy of the models test is presented. We used a combination of two Long Short-Term memory layers (LSTM), with dropout and varied the LSTM units and dropout values in the grid-search.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rnn-window" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rnn-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-rnn-window-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rnn-window-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: RNN prediction window search.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The RNN window search showed more competitive performance. In this case, a window of 30-days appears more robust overall, containing fewer worse performing models towards the extreme end. We therefore conducted an expanded grid-search using this window, the results of which are presented in <a href="#fig-rnn-configs" class="quarto-xref">Figure&nbsp;11</a> below. The grid-search hyperparameters are listed in <a href="#tbl-rnn-gs-param" class="quarto-xref">Table&nbsp;5</a>.</p>
<div class="cell">
<div id="tbl-rnn-gs-param" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rnn-gs-param-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Expanded grid-search hyperparameters and values.
</figcaption>
<div aria-describedby="tbl-rnn-gs-param-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-hover do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Hyperparameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">units1</td>
<td style="text-align: left;">16, 32, 64</td>
</tr>
<tr class="even">
<td style="text-align: left;">units2</td>
<td style="text-align: left;">16, 32, 64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drop1</td>
<td style="text-align: left;">0.3, 0.5, 0.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">drop2</td>
<td style="text-align: left;">0.3, 0.5, 0.7</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rnn-configs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rnn-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-rnn-configs-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rnn-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Top 30 configurations by validation accuracy for RNN.
</figcaption>
</figure>
</div>
</div>
</div>
<p>From the expanded grid-search, the best performing model achieved a validation accuracy of 64.8%. We fitted this model to the full training data and used that to predict onto the test set. Overall, we were satisfied with this search as the validation accuracy had not improved drastically compared to the initial window search; for example, the best model in the first stage reached roughly 60%.</p>
</section>
<section id="feedforward-multilayer-perceptron-neural-network" class="level3">
<h3 class="anchored" data-anchor-id="feedforward-multilayer-perceptron-neural-network">Feedforward Multilayer Perceptron Neural Network</h3>
<p>The FFNN-MLP architecture was optimised through a randomised grid-search to identify the most effective combination of hyperparameters. Candidate models has consistent input and output layers, while hidden layers varied. The input layer comprised 61 nodes, corresponding to the full set of hot-one encoded engineered predictor variables, plus bias.</p>
<p>The grid-search explored 2-4 hidden layers with neuron configurations such as [256, 128, 64], [512, 256, 128], and [128, 64]. The RectifierWithDropout activation promoted non-linearity and mitigated overfitting. The output layer had five neurons, with softmax to generate class probabilities.</p>
<p>To address class imbalance, each training observation was weighted inversely to its class frequency, increasing the influence of minority classes during optimisation.</p>
<p>The randomised grid-search evaluated a maximum of 216 candidate models, exploring a predefined hyperparameter space. Key hyperparameters and their search ranges are detailed in <a href="#tbl-ffnn-param" class="quarto-xref">Table&nbsp;6</a> .</p>
<div class="cell">
<div id="tbl-ffnn-param" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ffnn-param-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: FFNN-MLP Hyperparameter Grid.
</figcaption>
<div aria-describedby="tbl-ffnn-param-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-hover table-striped do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Hyperparameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">hidden</td>
<td style="text-align: left;">(128,128); (128,64); (64,32,16); (64,32)</td>
</tr>
<tr class="even">
<td style="text-align: left;">activation</td>
<td style="text-align: left;">RectifierWithDropout</td>
</tr>
<tr class="odd">
<td style="text-align: left;">l1</td>
<td style="text-align: left;">0, 1e-4, 1e-5</td>
</tr>
<tr class="even">
<td style="text-align: left;">l2</td>
<td style="text-align: left;">0, 1e-4, 1e-5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rate</td>
<td style="text-align: left;">0.01, 0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">input dropout ratio</td>
<td style="text-align: left;">0.1, 0.3, 0.5</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Models were trained for up to 200 epochs with early stopping, terminating if validation logloss did not improve by at least 1e-4 over 10 consecutive intervals.</p>
</section>
</section>
<section id="results-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="results-and-discussion">Results and Discussion</h2>
<section id="confusion-matrices" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices">Confusion Matrices</h3>
<p><a href="#fig-compare_cms" class="quarto-xref">Figure&nbsp;12</a> displays the confusion matrices for our 3 models. Our FFNN-MLP has a clearer diagonal, which is indicative of its stronger performance. The confusion matrix for the RNN is very diffused with widespread misclassifications. <a href="#tbl-overall_stats" class="quarto-xref">Table&nbsp;8</a> confirms this observation is indeed the case, as the RNN had the lowest accuracy (59%) and the FFNN-MLP had the highest (75%). The FFN-MLP accuracy just narrowly beats the accuracy of the forecasted values (FAH) which had an accuracy of 74. One limitation of the approach for evaluating the CNN and RNN is that, since the training and tests sets are not shuffled, and “High” risk avalanches are rare, there are no “High” risk avalanches in the test set. Therefore, the models ability to distinguish “High” risk cases is not assessed here.</p>
<p>The diagonal of the RNN is the weakest of them all. Its correct predictions are concentrated in “Low” (752) with spillover to “Moderate” (165), and its misclassifications are concentrated in “Low” (197) and “Moderate” (299) predictions which were actually “Moderate” instances. This tells us the model often confused “Moderate” cases as either “Low” (underestimated hazard) or “Moderate” (overestimated hazard).</p>
<p>In the case of the CNN, almost all predictions go to “Low”. There is a noticeable concentration on the diagonal for “Low” classifications (735), and a considerable concentration of “Moderate” classifications (270). On the off-diagonal, the model misclassified 205 “Low” instances as “Moderate”, and 148 “Moderate” instances as “Low”. Clearly, the CNN collapsed into predicting these two classes in many cases and often confused the two classes. The rows for these respective classes are all zeros. This shows that this model fell for imbalance bias, favouring the majority class “Low” and second most abundance “Moderate”.</p>
<p>The FFNN-MLP had some noticeable misclassifications between “Considerable-” and “Moderate”. We see that for 103 cases, the model predicted “Considerable-” instead of “Moderate”, which shows that it confuses those two classes a lot. Similarly, 112 Low cases were predicted as “Moderate”, another pair of classes the model struggles with.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-compare_cms" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-compare_cms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-compare_cms-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-compare_cms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Confusion Matrices Comparing the Final CNN, RNN, and Feed-Forward Models
</figcaption>
</figure>
</div>
</div>
</div>
<div id="tbl-accuracy_comparison" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-accuracy_comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7
</figcaption>
<div aria-describedby="tbl-accuracy_comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>

</div>
</div>
</figure>
</div>
</section>
<section id="overall-model-performance" class="level3">
<h3 class="anchored" data-anchor-id="overall-model-performance">Overall Model Performance</h3>
<p>In <a href="#tbl-overall_stats" class="quarto-xref">Table&nbsp;8</a> below, an overview of each model’s performance is presented. The FFNN-MLP performs best, achieving the highest accuracy, recall, specificity, and precision scores. The CNN serves as a middle ground, with acceptable accuracy but low recall. The RNN model performs the worst overall. In particular its recall and precision are fairly low which cast its practical reliability into doubt.</p>
<div class="cell">
<div id="tbl-overall_stats" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-overall_stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Overall Model performance Statistics
</figcaption>
<div aria-describedby="tbl-overall_stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Accuracy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Kappa</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Recall</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Precision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FFNN</td>
<td style="text-align: right;">0.754</td>
<td style="text-align: right;">0.645</td>
<td style="text-align: right;">0.618</td>
<td style="text-align: right;">0.934</td>
<td style="text-align: right;">0.633</td>
</tr>
<tr class="even">
<td style="text-align: left;">CNN</td>
<td style="text-align: right;">0.650</td>
<td style="text-align: right;">0.353</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">0.880</td>
<td style="text-align: right;">0.439</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RNN</td>
<td style="text-align: right;">0.594</td>
<td style="text-align: right;">0.222</td>
<td style="text-align: right;">0.368</td>
<td style="text-align: right;">0.849</td>
<td style="text-align: right;">0.311</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>The FFNN-MLP’s specificity was 0.934, the highest value observed. This tells us that this model is very good at ruling out cases that do not belong to a class. Its recall was 0.618, which means the model correctly identifies ~62% of true cases or in other words, it catches more actual danger levels compared to CNN and RNN. The CNN and RNN specificity scores were 0.880 and 0.849 respectively, which indicates they have fair ability to avoid false alarms of avalanche hazards, but not up to par with the FFNN-MLP’s ability. Notably, the RNN’s precision was 0.311, which means when it predicts, its only correct about 31% of the time. This means the RNN is wrong more often than its not. Contrast that with the CNN’s 0.439 precision (correct a little under half the time) and the FFNN-MLP’s 0.633 (correct around 63% of the time).</p>
</section>
<section id="model-statistics-by-class" class="level3">
<h3 class="anchored" data-anchor-id="model-statistics-by-class">Model Statistics by Class</h3>
<p>Looking at performance statistics by class can help us gain useful insight into each models strengths and weaknesses, providing a more detailed overview of model behaviour. <a href="#tbl-ffn_stats_by_class" class="quarto-xref">Table&nbsp;11</a>, <a href="#tbl-cnn_stats_by_class" class="quarto-xref">Table&nbsp;9</a> and <a href="#tbl-rnn_stats_by_class" class="quarto-xref">Table&nbsp;10</a> summarise our model statistics by class.</p>
<div class="cell">
<div id="tbl-cnn_stats_by_class" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cnn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: CNN Statistics by Class
</figcaption>
<div aria-describedby="tbl-cnn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pos Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Neg Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Precision</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Recall</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Balanced Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Class: Considerable -</td>
<td style="text-align: right;">0.0350877</td>
<td style="text-align: right;">0.9951824</td>
<td style="text-align: right;">0.3636364</td>
<td style="text-align: right;">0.9293059</td>
<td style="text-align: right;">0.3636364</td>
<td style="text-align: right;">0.0350877</td>
<td style="text-align: right;">0.0640000</td>
<td style="text-align: right;">0.0727505</td>
<td style="text-align: right;">0.0025526</td>
<td style="text-align: right;">0.0070198</td>
<td style="text-align: right;">0.5151351</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Considerable +</td>
<td style="text-align: right;">0.2368421</td>
<td style="text-align: right;">0.9444081</td>
<td style="text-align: right;">0.0957447</td>
<td style="text-align: right;">0.9803123</td>
<td style="text-align: right;">0.0957447</td>
<td style="text-align: right;">0.2368421</td>
<td style="text-align: right;">0.1363636</td>
<td style="text-align: right;">0.0242502</td>
<td style="text-align: right;">0.0057435</td>
<td style="text-align: right;">0.0599872</td>
<td style="text-align: right;">0.5906251</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: High</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Low</td>
<td style="text-align: right;">0.7736842</td>
<td style="text-align: right;">0.7179903</td>
<td style="text-align: right;">0.8085809</td>
<td style="text-align: right;">0.6732523</td>
<td style="text-align: right;">0.8085809</td>
<td style="text-align: right;">0.7736842</td>
<td style="text-align: right;">0.7907477</td>
<td style="text-align: right;">0.6062540</td>
<td style="text-align: right;">0.4690491</td>
<td style="text-align: right;">0.5800893</td>
<td style="text-align: right;">0.7458372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: Moderate</td>
<td style="text-align: right;">0.5806452</td>
<td style="text-align: right;">0.7431942</td>
<td style="text-align: right;">0.4882459</td>
<td style="text-align: right;">0.8076923</td>
<td style="text-align: right;">0.4882459</td>
<td style="text-align: right;">0.5806452</td>
<td style="text-align: right;">0.5304519</td>
<td style="text-align: right;">0.2967454</td>
<td style="text-align: right;">0.1723038</td>
<td style="text-align: right;">0.3529036</td>
<td style="text-align: right;">0.6619197</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-rnn_stats_by_class" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rnn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: RNN Statistics by Class
</figcaption>
<div aria-describedby="tbl-rnn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pos Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Neg Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Precision</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Recall</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Balanced Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Class: Considerable -</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.9986207</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.9276105</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: right;">0.0722969</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0012796</td>
<td style="text-align: right;">0.4993103</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Considerable +</td>
<td style="text-align: right;">0.3243243</td>
<td style="text-align: right;">0.9141547</td>
<td style="text-align: right;">0.0839161</td>
<td style="text-align: right;">0.9823944</td>
<td style="text-align: right;">0.0839161</td>
<td style="text-align: right;">0.3243243</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">0.0236724</td>
<td style="text-align: right;">0.0076775</td>
<td style="text-align: right;">0.0914907</td>
<td style="text-align: right;">0.6192395</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: High</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Low</td>
<td style="text-align: right;">0.7924131</td>
<td style="text-align: right;">0.5244300</td>
<td style="text-align: right;">0.7203065</td>
<td style="text-align: right;">0.6204239</td>
<td style="text-align: right;">0.7203065</td>
<td style="text-align: right;">0.7924131</td>
<td style="text-align: right;">0.7546412</td>
<td style="text-align: right;">0.6071657</td>
<td style="text-align: right;">0.4811260</td>
<td style="text-align: right;">0.6679463</td>
<td style="text-align: right;">0.6584215</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: Moderate</td>
<td style="text-align: right;">0.3556034</td>
<td style="text-align: right;">0.8098271</td>
<td style="text-align: right;">0.4411765</td>
<td style="text-align: right;">0.7485282</td>
<td style="text-align: right;">0.4411765</td>
<td style="text-align: right;">0.3556034</td>
<td style="text-align: right;">0.3937947</td>
<td style="text-align: right;">0.2968650</td>
<td style="text-align: right;">0.1055662</td>
<td style="text-align: right;">0.2392834</td>
<td style="text-align: right;">0.5827153</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-ffn_stats_by_class" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ffn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: FFNN Statistics by Class
</figcaption>
<div aria-describedby="tbl-ffn_stats_by_class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pos Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Neg Pred Value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Precision</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Recall</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">F1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Detection Prevalence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Balanced Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Class: Considerable -</td>
<td style="text-align: right;">0.7812500</td>
<td style="text-align: right;">0.8613782</td>
<td style="text-align: right;">0.5910165</td>
<td style="text-align: right;">0.9388646</td>
<td style="text-align: right;">0.5910165</td>
<td style="text-align: right;">0.7812500</td>
<td style="text-align: right;">0.6729475</td>
<td style="text-align: right;">0.2040816</td>
<td style="text-align: right;">0.1594388</td>
<td style="text-align: right;">0.2697704</td>
<td style="text-align: right;">0.8213141</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Considerable +</td>
<td style="text-align: right;">0.1772152</td>
<td style="text-align: right;">0.9865682</td>
<td style="text-align: right;">0.4117647</td>
<td style="text-align: right;">0.9576271</td>
<td style="text-align: right;">0.4117647</td>
<td style="text-align: right;">0.1772152</td>
<td style="text-align: right;">0.2477876</td>
<td style="text-align: right;">0.0503827</td>
<td style="text-align: right;">0.0089286</td>
<td style="text-align: right;">0.0216837</td>
<td style="text-align: right;">0.5818917</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: High</td>
<td style="text-align: right;">0.5600000</td>
<td style="text-align: right;">0.9909268</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.9928571</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.5600000</td>
<td style="text-align: right;">0.5283019</td>
<td style="text-align: right;">0.0159439</td>
<td style="text-align: right;">0.0089286</td>
<td style="text-align: right;">0.0178571</td>
<td style="text-align: right;">0.7754634</td>
</tr>
<tr class="even">
<td style="text-align: left;">Class: Low</td>
<td style="text-align: right;">0.8208270</td>
<td style="text-align: right;">0.9792350</td>
<td style="text-align: right;">0.9657658</td>
<td style="text-align: right;">0.8845015</td>
<td style="text-align: right;">0.9657658</td>
<td style="text-align: right;">0.8208270</td>
<td style="text-align: right;">0.8874172</td>
<td style="text-align: right;">0.4164541</td>
<td style="text-align: right;">0.3418367</td>
<td style="text-align: right;">0.3539541</td>
<td style="text-align: right;">0.9000310</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Class: Moderate</td>
<td style="text-align: right;">0.7515275</td>
<td style="text-align: right;">0.8523677</td>
<td style="text-align: right;">0.6988636</td>
<td style="text-align: right;">0.8826923</td>
<td style="text-align: right;">0.6988636</td>
<td style="text-align: right;">0.7515275</td>
<td style="text-align: right;">0.7242395</td>
<td style="text-align: right;">0.3131378</td>
<td style="text-align: right;">0.2353316</td>
<td style="text-align: right;">0.3367347</td>
<td style="text-align: right;">0.8019476</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>The CNN statistics detailed in <a href="#tbl-cnn_stats_by_class" class="quarto-xref">Table&nbsp;9</a> show that this model had mixed results. It was able to capture 82% of “Low” danger cases, which is the majority class, but its performance dropped sharply for the minority cases. Additionally, it only detected 3.5% of “Considerable -” cases.</p>
<p>On a class-by-class basis, the RNN performed poorly overall. It was able to catch about 79% of “Low” hazard cases. Beyond that, its performance collapsed. It missed all “Considerable-” cases (0 sensitivity overall). It only managed to detect 35% of “Moderate” cases. Moreover, its specificity for the “Low” class was just 52%, meaning it frequently mislabelled other classes as “Low”.</p>
<p>However, the FFNN-MLP (<a href="#tbl-ffn_stats_by_class" class="quarto-xref">Table&nbsp;11</a>) was especially good at recognising the common classes such as “Low” and “Moderate” danger, correctly identifying around 82% of “Low” cases and 75% of “Moderate” cases. This means that it both caught most of the true cases and rarely mislabelled other classes as these. However, the FFNN-MLP struggled with the rarer categories. For example, it only detected 18% of “Considerable +” cases. This suggests some model bias towards classes that were better represented.</p>
</section>
<section id="feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance">Feature Importance</h3>
<p>In <a href="#fig-var-imp-ffnn" class="quarto-xref">Figure&nbsp;13</a>, the feature importance plot from the FFNN-MLP is shown, for the first 30 most important variables.</p>
<p>The avalanche forecast varibles were highly influential. <em>FAH</em> dominates, with <em>FAH.Moderate</em>, <em>FAH.Low</em>, <em>FAH.Considerable-</em>, and <em>FAH.Considerable+</em> as the top predictors. <em>Altitude</em> <em>(Alt)</em> ranks just below <em>FAH</em>, while <em>snow.index</em> and the seasonal variables we constructed (<em>season12</em>, <em>season5</em>, <em>season3</em>) have moderate influence. This suggests seasonal trends do matter, but no single season dominates the prediction. If avalanches were restricted to one specific time/season window, we would have seen that season stand out much more.</p>
<p>Geographical area (<em>Area.Torridon</em>, <em>Area.Glencoe</em>) contributes minimally, indicating spatial differences are less important than <em>FAH</em>. <em>Precipitation</em> ranks lowest, adding little predictive power beyond snow index, which is clearly more influential.</p>
<p>Overall, the <em>FAH</em> drives predictions, followed by <em>altitude</em> and <em>snow.index</em>, with seasonal, spatial, and precipitation factors also adding influence to the model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-var-imp-ffnn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-var-imp-ffnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="DS4i_writeup_files/figure-html/fig-var-imp-ffnn-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-var-imp-ffnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Variable Importance for FFN-MLP.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="summary-of-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-findings">Summary of Findings</h3>
<p>In this study, we compared the ability of CNN, RNN, and FFNN-MLP models in predicting avalanches hazard levels. This was a multi-factorial investigation, as many different variables contribute to avalanche outcomes. The nature of this problem is sequential and we were able to preprocess that data to fit a time series context. We expected the CNN and RNN to outperform the FFNN-MLP since they have the added time series advantage.</p>
<p>The FFNN-MLP turned out to be the best-performing model overall. It showed the most balanced detection and achiebed the best performance across hazard levels. The CNN struggled with the minority classes and mainly acted as a majority-class (“Low” hazard) detector despite the controls put in place to re-weight the classes. This is unsatisfactory because in a real forecasting setting, it’s of great importance that we can detect the higher-risk cases. The RNN performed wrost overall, missing nearly all the minority class instances (“Considerable+”, “Considerable-”), and doing <em>fairly</em> well with the majority cases but still not as well as the other two models. This strongly disagrees with our initial hypothesis that sequential models would benefit from time series dependencies.</p>
<p>A clear strength across all models is that they handled the majority class fairly well. On the other hand, all three models showed clear bias toward the most common categories. None of them did especially well with the higher-risk, minority classes. The highlights a weakness in applying these models directly without addressing the class imbalance and customising the class weights more in favour of the minority classes could help counteract this measure.</p>
</section>
<section id="improvements-future-contributions" class="level3">
<h3 class="anchored" data-anchor-id="improvements-future-contributions">Improvements &amp; Future Contributions</h3>
<p>While the present study used only complete cases for modelling, avalanche forecasters in practice must often make predictions despite missing data. Imputation was considered, but fell outside the scope of evaluating NN performance. Developing an imputation model for this dataset could be a way of meaningfully improving its practical use, robustness, and accuracy overall. Secondly, Incorporating climate change effects by accounting for evolving weather and snowpack conditions alongside historical data could be a helpful tactic for researchers. Our models show that seasonal patterns are influential in predicting the risk. One reason this may be, is due to the evolving impact of climate change on the snow pack and ice condition. Furthermore, one may consider exploring region-specific models to reflect Scotland’s highly localized weather patterns and improve forecast reliability. Lastly, We restricted our hypothesis set to neural network models only, butthese may not be best suited to this data. Therefore, exploring alternative model types, such as gradient boosting or hybrid deep learning ensembles, to better handle categorical data and strengthen predictions could allow for more accurate prediction.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Our objective requires reliable detection across all avalanche danger levels, not just the majority ones. In this study, the FFNN-MLP came closest to meeting this requirement, but even it struggled with the minority, high-risk cases. Future work should focus on reducing class imbalance, exploring region-specific models, and experimenting with ensemble approaches to ensure that high-risk avalanche conditions are consistently and accurately detected.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><p>Bain, D. 2024. <em>Avalanche awareness in Scotland</em>. Sports Scotland Glenmore Lodge. Available: <a href="https://www.glenmorelodge.org.uk/avalanche-awareness-in-scotland/" class="uri">https://www.glenmorelodge.org.uk/avalanche-awareness-in-scotland/</a> [2025, September 11].</p></li>
<li><p>Beattie, B. 1976. The densification of a seasonal snowpack in the Cairngorms with relation to avalanches. B.Sc. (professional) dissertation. University of Lancaster.</p></li>
<li><p>Blagovechshenskiy, V., Medeu, A., Gulyayeva, T., Zhdanov, V., Ranova, S., Kamalbekova, A. &amp; Aldabergen, U. 2023. Application of artificial intelligence in the assessment and forecast of avalanche danger in the Ile Alatau Ridge. <em>Water</em>. 15(7). DOI: 10.3390/w15071438</p></li>
<li><p>Britannica. 2026. <em>Ben Nevis</em>. Available: <a href="https://www.britannica.com/place/Ben-Nevis" class="uri">https://www.britannica.com/place/Ben-Nevis</a> [2025, September 10].</p></li>
<li><p>Choubin, B., Borji, M., Mosavi, A., Sajedi-Hosseini, F., Singh, V.P. &amp; Shamshirband, S. 2019. Snow avalanche hazard prediction using machine learning methods. <em>Journal of Hydrology</em>. 577. DOI: 10.1016/j.jhydrol.2019.123929</p></li>
<li><p>Diggins, M. 2009. The challenges for Scottish avalanche forecasters observing a maritime snowpack. <em>Proceedings of the International Snow Science Workshop</em>. 22-24. Available: <a href="https://arc.lib.montana.edu/snow-science/objects/issw-2009-0024-0026.pdf" class="uri">https://arc.lib.montana.edu/snow-science/objects/issw-2009-0024-0026.pdf</a> [2025, September 10].</p></li>
<li><p>Fromm, R. &amp; Schonberger, C. 2022. Estimating the danger of snow avalanches with machine learning approach using a comprehensive snow cover model. <em>Machine Learning with Applications</em>. 10. DOI: 10.1016/j.mlwa.2022.100405</p></li>
<li><p>Gauthier, F., Laliberte, J. &amp; Meloche, F. 2025. Assessing the predictive capability of several machine learning algorithms to forecast snow avalanches using numerical weather prediction model in eastern Canada. <em>EGUsphere</em>. DOI: 10.5194/egusphere-2025-1572</p></li>
<li><p>Heierli, J., Purves, R.S., Felber, A. &amp; Kowalski, J. 2004. Verification of nearest-neighbours interpretations in avalanche forecasting. <em>Annals of Glaciology</em>. 38:84-88. DOI: 10.3189/172756404781815095</p></li>
<li><p>Helbig, N., van Herwijnen, A. &amp; Jonas, T. 2015. Forecasting wet-snow avalanche probability in mountainous terrain. <em>Cold Regions Science and Technology</em>. 120:219-226. DOI: 10.1016/j.coldregions.2015.07.001</p></li>
<li><p>Hendrick, M., Techel, F., Volpi, M., Olvski, T., Perez-Guillen, van Herwijnen, A. &amp; Schweizer, J. 2023. Automated prediction of wet-snow avalanche activity in the Swiss Alps. <em>Journal of Glaciology</em>. 69(277):1365-1378. DOI: 10.1017/jog.2023.24</p></li>
<li><p>Kala, M., Jain, S., Singh, A. &amp; Krishnan, N.C. 2025. Addressing class imbalance in avalanche forecasting. <em>Cold Regions Science and Technology</em>. 231. DOI: 10.1016/j.coldregions.2024.104411</p></li>
<li><p>Langmuir, E. 1970. Snow profiles in Scotland. <em>Weather</em>. 25(5):205-209. DOI: 10.1002/j.1477-8696.1970.tb03262.x</p></li>
<li><p>MetOffice. 2010. <em>UK regional climates</em>. Available: <a href="https://www.metoffice.gov.uk/research/climate/maps-and-data/regional-climates/index" class="uri">https://www.metoffice.gov.uk/research/climate/maps-and-data/regional-climates/index</a> [2025, September 11].</p></li>
<li><p>OpenAI. (2025a). ChatGPT (Sept 23 version) [Large language model]. https://chatgpt.com/share/68d59a8c-efa4-8004-a295-616e83f37afb</p></li>
<li><p>OpenAI. (2025b). ChatGPT (Sept 23 version) [Large language model]. https://chatgpt.com/share/68d59ad3-d50c-8004-b862-18966277b186</p></li>
<li><p>Pozdnoukhov, A., Purves, R.S. &amp; Kanevski, M. 2008. Applying machine learning methods to avalanche forecasting. <em>Annals of Glaciology</em>. 49:107-113. DOI: 10.3189/172756408787814870</p></li>
<li><p>Pozdnoukhov, A., Matasci, G., Kanevski, M. &amp; Purves, R.S. 2011. Spatio-temporal avalanche forecasting with Support Vector Machines. <em>Nat. Hazards Earth Syst. Sci.</em> 11:367-382. DOI: 10.5194/nhess-11-367-2011</p></li>
<li><p>Purves, R.S., Morrison, K.W., Moss, G. &amp; Wright, D.S.B. Nearest neighbours for avalanche forecasting in Scotland - Development, verification and optimisation of a model. <em>Cold Regions Science and Technology</em>. 37(3):343-355. DOI: 10.1016/S0165-232X(03)00075-2</p></li>
<li><p>Rahmati, O., Ghorbanzadeh, O., Teimurian, T., Mohammadi, F., Tiefenbacher, J.P., Falah, F., Pirasteh, S., Ngo, P.T.T. &amp; Bui, D.T. 2019. Spatial modeling of snow avalanche using machine learning models and geo-environmental factors: Comparison of effectiveness in two mountain regions. <em>Remote Sensing</em>. 11(24). DOI: 10.3390/rs11242995</p></li>
<li><p>Schirmer, M., Lehning, M. &amp; Schweizer, J. 2009. Statistical forecasting of regional avalanche danger using simulated snow-cover data. <em>Journal of Glaciology</em>. 55(193):761-768. DOI: 10.3189/002214309790152429</p></li>
<li><p>Scottish Avalanche Information Service. 2024. <em>Reviews of the winter season</em>. Available: <a href="https://www.sais.gov.uk/sais-annual-reports/" class="uri">https://www.sais.gov.uk/sais-annual-reports/</a> [2025, September 13].</p></li>
<li><p>Scottish Avalanche Information Service. 2025. <em>Avalanche information for the Scottish mountains</em>. Available: <a href="https://www.sais.gov.uk/" class="uri">https://www.sais.gov.uk/</a> [2025, September 5].</p></li>
<li><p>Scottish Government. 2011. <em>Scotland’s marine atlas: Information for the National Marine Plan</em>. Available: <a href="https://www.gov.scot/publications/scotlands-marine-atlas-information-national-marine-plan/pages/7/" class="uri">https://www.gov.scot/publications/scotlands-marine-atlas-information-national-marine-plan/pages/7/</a> [2025, September, 10].</p></li>
<li><p>Sharma, V., Kumar, S. &amp; Sushil, R. 2023. A neural network model for automated prediction of avalanche danger level. <em>Nat. Hazards Earth Syst. Sci.</em> 23:2523-2530. DOI: 10.5194/nhess-23-2523-2023</p></li>
<li><p>Singh, A. &amp; Ganju, A. 2008. Artificial neural networks for snow avalanche forecasting in Indian Himalaya. <em>Proceedings of the 12th International Conference of International Association for Computer Methods and Advances in Geomechanics (IACMAG)</em>. 1-6 October 2008. Gao, India. 1664-1670. Available: <a href="https://www.researchgate.net/publication/263651736_Artificial_Neural_Networks_for_Snow_Avalanche_Forecasting_in_Indian_Himalaya" class="uri">https://www.researchgate.net/publication/263651736_Artificial_Neural_Networks_for_Snow_Avalanche_Forecasting_in_Indian_Himalaya</a> [2025, September 13].</p></li>
<li><p>Spink, P.C. 1970. Scottish snowbeds in summer 1969. <em>Weather</em>. 25(5): 201-204. DOI: 10.1002/j.1477-8696.1970.tb03261.x</p></li>
<li><p>Tiwari, A., Arun, G. &amp; Vishwakarma, B.D. 2021. Parameter importance assessment improves efficacy of machine learning methods for predicting snow avalanche sites in Leh-Manali Highway, India. <em>Science of The Total Environment</em>. 794. DOI: 10.1016/j.scitotenv.2021.148738</p></li>
<li><p>Tu, J.V. 1996. Advantages and disadvantages of using artificial neural network versus logistic regression for predicting medical outcomes. <em>Journal of Clinical Epidemiology</em>. 49(11):1225-1231. DOI: 10.1016/S0895-4356(96)00002-9</p></li>
<li><p>Ward, R.G.W. 1980. Avalanche hazard in the Cairngorm Mountains, Scotland. <em>Journal of Glaciology</em>. 26(94):31-41. DOI: 10.3189/S0022143000201020</p></li>
<li><p>Ward, R.G.W. 1984a. Avalanche prediction in Scotland: I. A survey of avalanche activity. <em>Applied Geography</em>. 4(2):91-108. DOI: 10.1016/0143-6228(84)90016-X</p></li>
<li><p>Ward, R.G.W. 1984b. Avalanche prediction in Scotland: II. Development of a predictive model. <em>Applied Geography</em>. 4(2):109-133. DOI: 10.1016/0143-6228(84)90017-1</p></li>
<li><p>Ward, R.G.W., Langmuir, E.D.G. &amp; Beattie, B. 1985. Snow profiles and avalanche activity in the Cairngorm Mountains, Scotland. <em>Journal of Glaciology</em>. 31(107):18-27. DOI: 10.3189/S0022143000004949</p></li>
<li><p>Webster, H. 2020. <em>Avalanches in Scotland - interview with Mark Diggins</em>. Walkhighlands. Available: <a href="https://www.walkhighlands.co.uk/news/avalanches-in-scotland-interview-with-mark-diggins/" class="uri">https://www.walkhighlands.co.uk/news/avalanches-in-scotland-interview-with-mark-diggins/</a> [2025, September 10].</p></li>
<li><p>Wen, H., Wu, X., Liao, X., Wang, D., Huang, K. &amp; Wunnemann, B. 2022. Application of machine learning methods for snow avalanche susceptibility mapping in the Parlung Tsangpo catchement, southeastern Qinghai-Tibet Plateau. <em>Cold Regions Science and Technology</em>. 198. DOI: 10.1016/j.coldregions.2022.103535</p></li>
<li><p>Werritty, A. &amp; Sugden, D. 2012. Climate change and Scotland: Recent trends and impacts. <em>Earth and Environmental Science Transactions of The Royal Society of Edinburgh</em>. 103(2):133-147. DOI: 10.1017/S1755691013000030</p></li>
<li><p>WSL Institute for Snow and Avalanche Research SLF. 2016. <em>Scotland - Avalanche warning experts exchange</em>. Available: <a href="https://www.slf.ch/en/news/scotland-avalanche-warning-experts-exchange/?utm_source=chatgpt.com" class="uri">https://www.slf.ch/en/news/scotland-avalanche-warning-experts-exchange/?utm_source=chatgpt.com</a> [2025, September 12].</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>